# -------------------------------------------
bicycle_plugin: {
  vel_command_topic : "bicycle/vel_cmd",
  torque_command_topic : "bicycle/torque_cmd",
  publish_update_rate : 100, # Hz. Rate to publish joint states and tf's
}

bicycle : {
  wheel_radius : 0.35, #m
  wheel_base : 1.0, #m

  initial_conditions : {
    x : 0.0,        #m
    y : 0.0,        #m
    z : 0.0,        #m
    vel : 0.0,      #m/s
    roll : 0.0,     #deg
    heading : 0.0,  #deg from world x axis
    delta : 0.0,    #deg, steering angle
  },

  back_wheel_motor: {
    #PID velocity controller params
    kp : 4.0,
    ki : 0,
    kd : 0,
    i_max: 1000, # integral max limit
    i_min: -1000,
    u_max : 120, #Nm, max torque
    u_min : -120, #Nm
  },

  steering_motor: {
    #PID velocity controller params
    kp : 12.0,
    ki : 0.1,
    kd : 2,
    i_max: 1000, # integral max limit
    i_min: -1000,
    u_max : 120, #Nm, max torque
    u_min : -120, #Nm
  },
}
# -------------------------------------------

controller: {

  # State Space matrices
  A : [1,0,0,
       0,1,0,
       0,0,1],
  B : [0,0],
  C : [0,0,1,
       1,0,0],
  D : [0, 0],

  update_rate: 100, # Hz
  sigma: 0.01,  # Dirty derivative parameters

  lqr_controller : {
    Q : [0, 0, 0,
        0, 0, 0,
        0, 0, 0],
    R : [0, 0, 0]
  }
}





